### ISSUE TITLE
Check read/write semantics

### ISSUE THREAD

**Issue by OskarCarl** [vs-ude/mic-1-toolbox#148]
What happens when we `rd; wr;` ? The read should probably complete before the write op, but is this defined in Tanenbaum's book?

**Comment by Zeusmaxhallo** [comment]
Im Tannenbaum stehen keine Informationen wie lange Write dauert, es wird nur Read behandelt.

Es wird nur gesagt, dass Write und Read nicht gleichzeitig benutzt werden sollen:
"However, trying to read and write the same byte simultaneously gives
undefined results."
