### ISSUE TITLE
Refactor compiler pipeline

### ISSUE THREAD

**Issue by OskarCarl** [vs-ude/mic-1-toolbox#190]
Rework the pipeline:
- Tokenizer also creates newline tokens
  - Tokens include the line in the original code
- Parser should be split into an Abstract Syntax Tree generator and a semantic checker
  - Parser does only syntax checks
  - Semantic checker checks the AST's validity
- Semantic checker needs two passes, to be able to properly reference labels and method calls

Blocks #183 #156

**Comment by YasinKavuk** [comment]
The parser should also be split to an compiler that takes the AST created and translates it to Machine Code that can be processed by the MIC-1.
