### ISSUE TITLE
Visualisierung Test

### ISSUE THREAD

**Issue by OskarCarl** [vs-ude/mic-1-toolbox#21]
4 Pkt

Test der Möglichkeiten (1 reicht) zur Visualisierung per SVG. Noch keine vollständige Integration.
Ziel: Doku "Wie setzen wir das um?"

**Comment by Zeusmaxhallo** [comment]
Test Projekt: https://stackblitz.com/edit/angular-ivy-pz6snn?file=src/app/app.component.html
