### ISSUE TITLE
Recherche: Unit Test

### ISSUE THREAD

**Issue by OskarCarl** [vs-ude/mic-1-toolbox#24]
5 Pkt.

Wie funktionieren unit Test in Angular? Reicht das aus?

**Comment by YasinKavuk** [comment]
Angular component tests works by using "ng test". "ng test" builds the application in watch mode and launches the Karma test runner. Karma is a testing environment. By default you need the Chrome browser. You also might to need to set your CHROME_BIN Enviromental Variable or you might get an error.

"ng test" will than test every spec.ts files. So if someone wants to write an individual test, they would need to write it in the spec.ts file of this specific component. There is a default test that is already setup when you generate the component. The default just instantiates the component and tests if it exists or not. Services can also be tested the same way.

The tests can be configured in the karma.conf.js file.

- Documentantion of Angular Testing: https://angular.io/guide/testing
- Description of Angular testing features: https://angular.io/guide/testing-utility-apis
- usefull Youtube video: https://www.youtube.com/watch?v=xJ45MGDAi6c

**Comment by YasinKavuk** [comment]
https://testing-angular.com/target-audience/#target-audience
