### ISSUE TITLE
Recherche: speicherlimits

### ISSUE THREAD

**Issue by OskarCarl** [vs-ude/mic-1-toolbox#35]
Wie viel Speicher darf eine Seite in Browsern verbrauchen? Kann das zum Problem werden. Safari, Firefox, und Chrome betrachten

**Comment by Zeusmaxhallo** [comment]
"5MB per app per browser. According to the [HTML5 spec](http://www.w3.org/TR/2009/WD-webstorage-20091222/#the-storage-interface), this limit can be increased by the user when needed; however, only a few browsers support this"
