### ISSUE TITLE
Director Service

### ISSUE THREAD

**Issue by OskarCarl** [vs-ude/mic-1-toolbox#36]
Component in Service umwandeln.

**Comment by YasinKavuk** [comment]
Director Service ist schon da und hat auch schon eine funktionierende Step Funktion und kann auch den Register und Stack modifizieren.
 
Soll noch:
- Geparsten Macroassembler Code von der Main Memory lesen und mit den Adressen dort im Control Store die Microprograms ausführen. Dabei falls nötig auch die Parameter der Instruktions verwenden.
- Soll eine Run Funktion haben welches die Step Funktion x mal in der Sekunde ausführt.
