### ISSUE TITLE
Makrocode Parser

### ISSUE THREAD

**Issue by OskarCarl** [vs-ude/mic-1-toolbox#38]
Oder Interpreter, je nach dem was geeigneter ist.

**Comment by YasinKavuk** [comment]
**Kann jetzt:**
- Variablen und Konstanten in die Main Memory speichern
- IAND und DUP Instruktion in die Adressenform umwandeln.


**Soll noch:**
- Alle Instruktionen in die Adressform umwandeln
- Variablen und Konstanten auch in Adressofrm umwandeln wenn diese als Parameter für Instruktionen benutzt werden
- Alles in die Main Memory speichern

**Comment by YasinKavuk** [comment]
Seit Commit 9c91b5938237f5f42fae81c24dac41b2f7b7025c kann der Macroparser alle Tokens in Adressen umwandeln und in die Main Memory speichern.
Das einzige was noch nicht geht das die Parameter eines Methodenaufrufs übergeben werden.

**Comment by YasinKavuk** [comment]
Der ganze macro Parser wurde seit letzer Woche überarbeitet. Instructions werden mit den Adressen richtig gespeichert. Bei den Parametern werden die meisten richtig gespeichert in die Main Memory. Es gibt Folgende Fälle:
- [ ] byte
- [ ] offset
- [ ] varnum
- [ ] const
- [ ] disp
- [ ] index
