### ISSUE TITLE
Integration Test fixen

### ISSUE THREAD

**Issue by OskarCarl** [vs-ude/mic-1-toolbox#44]

**Comment by YasinKavuk** [comment]
The integration test is actually more a e2e test. The currently used broken "integration test" should be removed and replaced with a cypress e2e test.

**Comment by YasinKavuk** [comment]
This integration test is not working anymore and is not the best way to do. The intention of this test is to test the complete workflow of the app. This should be done by a e2e test. This test will be removed and replaced by a cypress e2e test.
