### ISSUE TITLE
Dev/Prod Mode Versionen

### ISSUE THREAD

**Issue by Ataraxxis** [vs-ude/mic-1-toolbox#73]
Debug Buttons/Logs nur im Dev Mode anzeigen.
https://stackoverflow.com/questions/39535386/how-to-check-if-angular-application-running-in-production-or-development-mode

**Comment by YasinKavuk** [comment]
isDevMode was not used directly but when dev mode is active the console.log, console.table and console.group functions turn into empty functions and all the console output is not shown. 

This closes the Issue.
