### ISSUE TITLE
Network dependencies

### ISSUE THREAD

**Issue by Ataraxxis** [vs-ude/mic-1-toolbox#91]
Check all dependencies (fonts, icons, libs)
Strip everything possible or change to local files.

**Comment by Ataraxxis** [comment]
svg dependency: xmlns="http://www.w3.org/2000/svg"

**Comment by YasinKavuk** [comment]
The xmlns="http://www.w3.org/2000/svg" should not be changed or removed.
This url is not used for connecting somewhere to the web. It's just a XML-namespace. 
Changing it will make the SVG file invalid

![Screenshot from 2023-04-14 19-49-55](https://user-images.githubusercontent.com/33101574/232119956-fa178c5f-2a6f-4adb-9f51-f2d086e1b35e.png)

source: https://www.w3.org/TR/xml-names/ and https://stackoverflow.com/questions/39573020/requested-https-www-w3-org-2000-svg-found-http-www-w3-org-2000-svg
