### ISSUE TITLE
Line highlighting while stepping

### ISSUE THREAD

**Issue by Ataraxxis** [vs-ude/mic-1-toolbox#93]
Highlight Code lines (micro when micro step, macro when macro step)

**Comment by Ataraxxis** [comment]
Controller (ng service)
Trigger on Button Click/Error/Breakpoint etc
Priority highlighting: Error > Breakpoint > Current Step Line (Only Step Mode)

**Comment by YasinKavuk** [comment]
Lost for Macro steps after merging pull request #201
